package com.ch.computer.pojo;

import java.util.ArrayList;
import java.util.List;

public class ChassisExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public ChassisExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andChIdIsNull() {
            addCriterion("ch_id is null");
            return (Criteria) this;
        }

        public Criteria andChIdIsNotNull() {
            addCriterion("ch_id is not null");
            return (Criteria) this;
        }

        public Criteria andChIdEqualTo(Integer value) {
            addCriterion("ch_id =", value, "chId");
            return (Criteria) this;
        }

        public Criteria andChIdNotEqualTo(Integer value) {
            addCriterion("ch_id <>", value, "chId");
            return (Criteria) this;
        }

        public Criteria andChIdGreaterThan(Integer value) {
            addCriterion("ch_id >", value, "chId");
            return (Criteria) this;
        }

        public Criteria andChIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ch_id >=", value, "chId");
            return (Criteria) this;
        }

        public Criteria andChIdLessThan(Integer value) {
            addCriterion("ch_id <", value, "chId");
            return (Criteria) this;
        }

        public Criteria andChIdLessThanOrEqualTo(Integer value) {
            addCriterion("ch_id <=", value, "chId");
            return (Criteria) this;
        }

        public Criteria andChIdIn(List<Integer> values) {
            addCriterion("ch_id in", values, "chId");
            return (Criteria) this;
        }

        public Criteria andChIdNotIn(List<Integer> values) {
            addCriterion("ch_id not in", values, "chId");
            return (Criteria) this;
        }

        public Criteria andChIdBetween(Integer value1, Integer value2) {
            addCriterion("ch_id between", value1, value2, "chId");
            return (Criteria) this;
        }

        public Criteria andChIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ch_id not between", value1, value2, "chId");
            return (Criteria) this;
        }

        public Criteria andChNameIsNull() {
            addCriterion("ch_name is null");
            return (Criteria) this;
        }

        public Criteria andChNameIsNotNull() {
            addCriterion("ch_name is not null");
            return (Criteria) this;
        }

        public Criteria andChNameEqualTo(String value) {
            addCriterion("ch_name =", value, "chName");
            return (Criteria) this;
        }

        public Criteria andChNameNotEqualTo(String value) {
            addCriterion("ch_name <>", value, "chName");
            return (Criteria) this;
        }

        public Criteria andChNameGreaterThan(String value) {
            addCriterion("ch_name >", value, "chName");
            return (Criteria) this;
        }

        public Criteria andChNameGreaterThanOrEqualTo(String value) {
            addCriterion("ch_name >=", value, "chName");
            return (Criteria) this;
        }

        public Criteria andChNameLessThan(String value) {
            addCriterion("ch_name <", value, "chName");
            return (Criteria) this;
        }

        public Criteria andChNameLessThanOrEqualTo(String value) {
            addCriterion("ch_name <=", value, "chName");
            return (Criteria) this;
        }

        public Criteria andChNameLike(String value) {
            addCriterion("ch_name like", value, "chName");
            return (Criteria) this;
        }

        public Criteria andChNameNotLike(String value) {
            addCriterion("ch_name not like", value, "chName");
            return (Criteria) this;
        }

        public Criteria andChNameIn(List<String> values) {
            addCriterion("ch_name in", values, "chName");
            return (Criteria) this;
        }

        public Criteria andChNameNotIn(List<String> values) {
            addCriterion("ch_name not in", values, "chName");
            return (Criteria) this;
        }

        public Criteria andChNameBetween(String value1, String value2) {
            addCriterion("ch_name between", value1, value2, "chName");
            return (Criteria) this;
        }

        public Criteria andChNameNotBetween(String value1, String value2) {
            addCriterion("ch_name not between", value1, value2, "chName");
            return (Criteria) this;
        }

        public Criteria andChFactoryIsNull() {
            addCriterion("ch_factory is null");
            return (Criteria) this;
        }

        public Criteria andChFactoryIsNotNull() {
            addCriterion("ch_factory is not null");
            return (Criteria) this;
        }

        public Criteria andChFactoryEqualTo(String value) {
            addCriterion("ch_factory =", value, "chFactory");
            return (Criteria) this;
        }

        public Criteria andChFactoryNotEqualTo(String value) {
            addCriterion("ch_factory <>", value, "chFactory");
            return (Criteria) this;
        }

        public Criteria andChFactoryGreaterThan(String value) {
            addCriterion("ch_factory >", value, "chFactory");
            return (Criteria) this;
        }

        public Criteria andChFactoryGreaterThanOrEqualTo(String value) {
            addCriterion("ch_factory >=", value, "chFactory");
            return (Criteria) this;
        }

        public Criteria andChFactoryLessThan(String value) {
            addCriterion("ch_factory <", value, "chFactory");
            return (Criteria) this;
        }

        public Criteria andChFactoryLessThanOrEqualTo(String value) {
            addCriterion("ch_factory <=", value, "chFactory");
            return (Criteria) this;
        }

        public Criteria andChFactoryLike(String value) {
            addCriterion("ch_factory like", value, "chFactory");
            return (Criteria) this;
        }

        public Criteria andChFactoryNotLike(String value) {
            addCriterion("ch_factory not like", value, "chFactory");
            return (Criteria) this;
        }

        public Criteria andChFactoryIn(List<String> values) {
            addCriterion("ch_factory in", values, "chFactory");
            return (Criteria) this;
        }

        public Criteria andChFactoryNotIn(List<String> values) {
            addCriterion("ch_factory not in", values, "chFactory");
            return (Criteria) this;
        }

        public Criteria andChFactoryBetween(String value1, String value2) {
            addCriterion("ch_factory between", value1, value2, "chFactory");
            return (Criteria) this;
        }

        public Criteria andChFactoryNotBetween(String value1, String value2) {
            addCriterion("ch_factory not between", value1, value2, "chFactory");
            return (Criteria) this;
        }

        public Criteria andChParamIsNull() {
            addCriterion("ch_param is null");
            return (Criteria) this;
        }

        public Criteria andChParamIsNotNull() {
            addCriterion("ch_param is not null");
            return (Criteria) this;
        }

        public Criteria andChParamEqualTo(String value) {
            addCriterion("ch_param =", value, "chParam");
            return (Criteria) this;
        }

        public Criteria andChParamNotEqualTo(String value) {
            addCriterion("ch_param <>", value, "chParam");
            return (Criteria) this;
        }

        public Criteria andChParamGreaterThan(String value) {
            addCriterion("ch_param >", value, "chParam");
            return (Criteria) this;
        }

        public Criteria andChParamGreaterThanOrEqualTo(String value) {
            addCriterion("ch_param >=", value, "chParam");
            return (Criteria) this;
        }

        public Criteria andChParamLessThan(String value) {
            addCriterion("ch_param <", value, "chParam");
            return (Criteria) this;
        }

        public Criteria andChParamLessThanOrEqualTo(String value) {
            addCriterion("ch_param <=", value, "chParam");
            return (Criteria) this;
        }

        public Criteria andChParamLike(String value) {
            addCriterion("ch_param like", value, "chParam");
            return (Criteria) this;
        }

        public Criteria andChParamNotLike(String value) {
            addCriterion("ch_param not like", value, "chParam");
            return (Criteria) this;
        }

        public Criteria andChParamIn(List<String> values) {
            addCriterion("ch_param in", values, "chParam");
            return (Criteria) this;
        }

        public Criteria andChParamNotIn(List<String> values) {
            addCriterion("ch_param not in", values, "chParam");
            return (Criteria) this;
        }

        public Criteria andChParamBetween(String value1, String value2) {
            addCriterion("ch_param between", value1, value2, "chParam");
            return (Criteria) this;
        }

        public Criteria andChParamNotBetween(String value1, String value2) {
            addCriterion("ch_param not between", value1, value2, "chParam");
            return (Criteria) this;
        }

        public Criteria andChPriceIsNull() {
            addCriterion("ch_price is null");
            return (Criteria) this;
        }

        public Criteria andChPriceIsNotNull() {
            addCriterion("ch_price is not null");
            return (Criteria) this;
        }

        public Criteria andChPriceEqualTo(Double value) {
            addCriterion("ch_price =", value, "chPrice");
            return (Criteria) this;
        }

        public Criteria andChPriceNotEqualTo(Double value) {
            addCriterion("ch_price <>", value, "chPrice");
            return (Criteria) this;
        }

        public Criteria andChPriceGreaterThan(Double value) {
            addCriterion("ch_price >", value, "chPrice");
            return (Criteria) this;
        }

        public Criteria andChPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("ch_price >=", value, "chPrice");
            return (Criteria) this;
        }

        public Criteria andChPriceLessThan(Double value) {
            addCriterion("ch_price <", value, "chPrice");
            return (Criteria) this;
        }

        public Criteria andChPriceLessThanOrEqualTo(Double value) {
            addCriterion("ch_price <=", value, "chPrice");
            return (Criteria) this;
        }

        public Criteria andChPriceIn(List<Double> values) {
            addCriterion("ch_price in", values, "chPrice");
            return (Criteria) this;
        }

        public Criteria andChPriceNotIn(List<Double> values) {
            addCriterion("ch_price not in", values, "chPrice");
            return (Criteria) this;
        }

        public Criteria andChPriceBetween(Double value1, Double value2) {
            addCriterion("ch_price between", value1, value2, "chPrice");
            return (Criteria) this;
        }

        public Criteria andChPriceNotBetween(Double value1, Double value2) {
            addCriterion("ch_price not between", value1, value2, "chPrice");
            return (Criteria) this;
        }

        public Criteria andChInventoryIsNull() {
            addCriterion("ch_inventory is null");
            return (Criteria) this;
        }

        public Criteria andChInventoryIsNotNull() {
            addCriterion("ch_inventory is not null");
            return (Criteria) this;
        }

        public Criteria andChInventoryEqualTo(Integer value) {
            addCriterion("ch_inventory =", value, "chInventory");
            return (Criteria) this;
        }

        public Criteria andChInventoryNotEqualTo(Integer value) {
            addCriterion("ch_inventory <>", value, "chInventory");
            return (Criteria) this;
        }

        public Criteria andChInventoryGreaterThan(Integer value) {
            addCriterion("ch_inventory >", value, "chInventory");
            return (Criteria) this;
        }

        public Criteria andChInventoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("ch_inventory >=", value, "chInventory");
            return (Criteria) this;
        }

        public Criteria andChInventoryLessThan(Integer value) {
            addCriterion("ch_inventory <", value, "chInventory");
            return (Criteria) this;
        }

        public Criteria andChInventoryLessThanOrEqualTo(Integer value) {
            addCriterion("ch_inventory <=", value, "chInventory");
            return (Criteria) this;
        }

        public Criteria andChInventoryIn(List<Integer> values) {
            addCriterion("ch_inventory in", values, "chInventory");
            return (Criteria) this;
        }

        public Criteria andChInventoryNotIn(List<Integer> values) {
            addCriterion("ch_inventory not in", values, "chInventory");
            return (Criteria) this;
        }

        public Criteria andChInventoryBetween(Integer value1, Integer value2) {
            addCriterion("ch_inventory between", value1, value2, "chInventory");
            return (Criteria) this;
        }

        public Criteria andChInventoryNotBetween(Integer value1, Integer value2) {
            addCriterion("ch_inventory not between", value1, value2, "chInventory");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chassis
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 07 22:26:32 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}