package com.ch.computer.pojo;

public class Chassis {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chassis.ch_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Integer chId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chassis.ch_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String chName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chassis.ch_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String chFactory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chassis.ch_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String chParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chassis.ch_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Double chPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chassis.ch_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Integer chInventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chassis.ch_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String chImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chassis.ch_id
     *
     * @return the value of chassis.ch_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Integer getChId() {
        return chId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chassis.ch_id
     *
     * @param chId the value for chassis.ch_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setChId(Integer chId) {
        this.chId = chId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chassis.ch_name
     *
     * @return the value of chassis.ch_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getChName() {
        return chName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chassis.ch_name
     *
     * @param chName the value for chassis.ch_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setChName(String chName) {
        this.chName = chName == null ? null : chName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chassis.ch_factory
     *
     * @return the value of chassis.ch_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getChFactory() {
        return chFactory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chassis.ch_factory
     *
     * @param chFactory the value for chassis.ch_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setChFactory(String chFactory) {
        this.chFactory = chFactory == null ? null : chFactory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chassis.ch_param
     *
     * @return the value of chassis.ch_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getChParam() {
        return chParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chassis.ch_param
     *
     * @param chParam the value for chassis.ch_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setChParam(String chParam) {
        this.chParam = chParam == null ? null : chParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chassis.ch_price
     *
     * @return the value of chassis.ch_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Double getChPrice() {
        return chPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chassis.ch_price
     *
     * @param chPrice the value for chassis.ch_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setChPrice(Double chPrice) {
        this.chPrice = chPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chassis.ch_inventory
     *
     * @return the value of chassis.ch_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Integer getChInventory() {
        return chInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chassis.ch_inventory
     *
     * @param chInventory the value for chassis.ch_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setChInventory(Integer chInventory) {
        this.chInventory = chInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chassis.ch_img
     *
     * @return the value of chassis.ch_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getChImg() {
        return chImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chassis.ch_img
     *
     * @param chImg the value for chassis.ch_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setChImg(String chImg) {
        this.chImg = chImg == null ? null : chImg.trim();
    }
}