package com.ch.computer.pojo;

public class Cpu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpu.c_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Integer cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpu.c_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String cName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpu.c_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String cFactory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpu.c_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String cParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpu.c_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Double cPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpu.c_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Integer cInventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpu.c_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String cImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpu.c_id
     *
     * @return the value of cpu.c_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpu.c_id
     *
     * @param cId the value for cpu.c_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpu.c_name
     *
     * @return the value of cpu.c_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpu.c_name
     *
     * @param cName the value for cpu.c_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpu.c_factory
     *
     * @return the value of cpu.c_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getcFactory() {
        return cFactory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpu.c_factory
     *
     * @param cFactory the value for cpu.c_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setcFactory(String cFactory) {
        this.cFactory = cFactory == null ? null : cFactory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpu.c_param
     *
     * @return the value of cpu.c_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getcParam() {
        return cParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpu.c_param
     *
     * @param cParam the value for cpu.c_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setcParam(String cParam) {
        this.cParam = cParam == null ? null : cParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpu.c_price
     *
     * @return the value of cpu.c_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Double getcPrice() {
        return cPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpu.c_price
     *
     * @param cPrice the value for cpu.c_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setcPrice(Double cPrice) {
        this.cPrice = cPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpu.c_inventory
     *
     * @return the value of cpu.c_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Integer getcInventory() {
        return cInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpu.c_inventory
     *
     * @param cInventory the value for cpu.c_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setcInventory(Integer cInventory) {
        this.cInventory = cInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpu.c_img
     *
     * @return the value of cpu.c_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getcImg() {
        return cImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpu.c_img
     *
     * @param cImg the value for cpu.c_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setcImg(String cImg) {
        this.cImg = cImg == null ? null : cImg.trim();
    }
}