package com.ch.computer.pojo;

public class Disk {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disk.d_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Integer dId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disk.d_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String dName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disk.d_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String dFactory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disk.d_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String dParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disk.d_type
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Integer dType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disk.d_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Double dPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disk.d_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Integer dInventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disk.d_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String dImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disk.d_id
     *
     * @return the value of disk.d_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disk.d_id
     *
     * @param dId the value for disk.d_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disk.d_name
     *
     * @return the value of disk.d_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getdName() {
        return dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disk.d_name
     *
     * @param dName the value for disk.d_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setdName(String dName) {
        this.dName = dName == null ? null : dName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disk.d_factory
     *
     * @return the value of disk.d_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getdFactory() {
        return dFactory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disk.d_factory
     *
     * @param dFactory the value for disk.d_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setdFactory(String dFactory) {
        this.dFactory = dFactory == null ? null : dFactory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disk.d_param
     *
     * @return the value of disk.d_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getdParam() {
        return dParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disk.d_param
     *
     * @param dParam the value for disk.d_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setdParam(String dParam) {
        this.dParam = dParam == null ? null : dParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disk.d_type
     *
     * @return the value of disk.d_type
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Integer getdType() {
        return dType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disk.d_type
     *
     * @param dType the value for disk.d_type
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setdType(Integer dType) {
        this.dType = dType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disk.d_price
     *
     * @return the value of disk.d_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Double getdPrice() {
        return dPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disk.d_price
     *
     * @param dPrice the value for disk.d_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setdPrice(Double dPrice) {
        this.dPrice = dPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disk.d_inventory
     *
     * @return the value of disk.d_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Integer getdInventory() {
        return dInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disk.d_inventory
     *
     * @param dInventory the value for disk.d_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setdInventory(Integer dInventory) {
        this.dInventory = dInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disk.d_img
     *
     * @return the value of disk.d_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getdImg() {
        return dImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disk.d_img
     *
     * @param dImg the value for disk.d_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setdImg(String dImg) {
        this.dImg = dImg == null ? null : dImg.trim();
    }
}