package com.ch.computer.pojo;

public class Fan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fan.f_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Integer fId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fan.f_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String fName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fan.f_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String fFactory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fan.f_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String fParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fan.f_num
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Integer fNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fan.f_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Double fPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fan.f_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Integer fInventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fan.f_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String fImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fan.f_id
     *
     * @return the value of fan.f_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fan.f_id
     *
     * @param fId the value for fan.f_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fan.f_name
     *
     * @return the value of fan.f_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getfName() {
        return fName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fan.f_name
     *
     * @param fName the value for fan.f_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setfName(String fName) {
        this.fName = fName == null ? null : fName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fan.f_factory
     *
     * @return the value of fan.f_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getfFactory() {
        return fFactory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fan.f_factory
     *
     * @param fFactory the value for fan.f_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setfFactory(String fFactory) {
        this.fFactory = fFactory == null ? null : fFactory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fan.f_param
     *
     * @return the value of fan.f_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getfParam() {
        return fParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fan.f_param
     *
     * @param fParam the value for fan.f_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setfParam(String fParam) {
        this.fParam = fParam == null ? null : fParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fan.f_num
     *
     * @return the value of fan.f_num
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Integer getfNum() {
        return fNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fan.f_num
     *
     * @param fNum the value for fan.f_num
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setfNum(Integer fNum) {
        this.fNum = fNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fan.f_price
     *
     * @return the value of fan.f_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Double getfPrice() {
        return fPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fan.f_price
     *
     * @param fPrice the value for fan.f_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setfPrice(Double fPrice) {
        this.fPrice = fPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fan.f_inventory
     *
     * @return the value of fan.f_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Integer getfInventory() {
        return fInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fan.f_inventory
     *
     * @param fInventory the value for fan.f_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setfInventory(Integer fInventory) {
        this.fInventory = fInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fan.f_img
     *
     * @return the value of fan.f_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getfImg() {
        return fImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fan.f_img
     *
     * @param fImg the value for fan.f_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setfImg(String fImg) {
        this.fImg = fImg == null ? null : fImg.trim();
    }
}