package com.ch.computer.pojo;

import java.util.ArrayList;
import java.util.List;

public class GraphicsCardExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table graphics_card
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table graphics_card
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table graphics_card
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graphics_card
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public GraphicsCardExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graphics_card
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graphics_card
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graphics_card
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graphics_card
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graphics_card
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graphics_card
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graphics_card
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graphics_card
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graphics_card
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graphics_card
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table graphics_card
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGcIdIsNull() {
            addCriterion("gc_id is null");
            return (Criteria) this;
        }

        public Criteria andGcIdIsNotNull() {
            addCriterion("gc_id is not null");
            return (Criteria) this;
        }

        public Criteria andGcIdEqualTo(Integer value) {
            addCriterion("gc_id =", value, "gcId");
            return (Criteria) this;
        }

        public Criteria andGcIdNotEqualTo(Integer value) {
            addCriterion("gc_id <>", value, "gcId");
            return (Criteria) this;
        }

        public Criteria andGcIdGreaterThan(Integer value) {
            addCriterion("gc_id >", value, "gcId");
            return (Criteria) this;
        }

        public Criteria andGcIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("gc_id >=", value, "gcId");
            return (Criteria) this;
        }

        public Criteria andGcIdLessThan(Integer value) {
            addCriterion("gc_id <", value, "gcId");
            return (Criteria) this;
        }

        public Criteria andGcIdLessThanOrEqualTo(Integer value) {
            addCriterion("gc_id <=", value, "gcId");
            return (Criteria) this;
        }

        public Criteria andGcIdIn(List<Integer> values) {
            addCriterion("gc_id in", values, "gcId");
            return (Criteria) this;
        }

        public Criteria andGcIdNotIn(List<Integer> values) {
            addCriterion("gc_id not in", values, "gcId");
            return (Criteria) this;
        }

        public Criteria andGcIdBetween(Integer value1, Integer value2) {
            addCriterion("gc_id between", value1, value2, "gcId");
            return (Criteria) this;
        }

        public Criteria andGcIdNotBetween(Integer value1, Integer value2) {
            addCriterion("gc_id not between", value1, value2, "gcId");
            return (Criteria) this;
        }

        public Criteria andGcNameIsNull() {
            addCriterion("gc_name is null");
            return (Criteria) this;
        }

        public Criteria andGcNameIsNotNull() {
            addCriterion("gc_name is not null");
            return (Criteria) this;
        }

        public Criteria andGcNameEqualTo(String value) {
            addCriterion("gc_name =", value, "gcName");
            return (Criteria) this;
        }

        public Criteria andGcNameNotEqualTo(String value) {
            addCriterion("gc_name <>", value, "gcName");
            return (Criteria) this;
        }

        public Criteria andGcNameGreaterThan(String value) {
            addCriterion("gc_name >", value, "gcName");
            return (Criteria) this;
        }

        public Criteria andGcNameGreaterThanOrEqualTo(String value) {
            addCriterion("gc_name >=", value, "gcName");
            return (Criteria) this;
        }

        public Criteria andGcNameLessThan(String value) {
            addCriterion("gc_name <", value, "gcName");
            return (Criteria) this;
        }

        public Criteria andGcNameLessThanOrEqualTo(String value) {
            addCriterion("gc_name <=", value, "gcName");
            return (Criteria) this;
        }

        public Criteria andGcNameLike(String value) {
            addCriterion("gc_name like", value, "gcName");
            return (Criteria) this;
        }

        public Criteria andGcNameNotLike(String value) {
            addCriterion("gc_name not like", value, "gcName");
            return (Criteria) this;
        }

        public Criteria andGcNameIn(List<String> values) {
            addCriterion("gc_name in", values, "gcName");
            return (Criteria) this;
        }

        public Criteria andGcNameNotIn(List<String> values) {
            addCriterion("gc_name not in", values, "gcName");
            return (Criteria) this;
        }

        public Criteria andGcNameBetween(String value1, String value2) {
            addCriterion("gc_name between", value1, value2, "gcName");
            return (Criteria) this;
        }

        public Criteria andGcNameNotBetween(String value1, String value2) {
            addCriterion("gc_name not between", value1, value2, "gcName");
            return (Criteria) this;
        }

        public Criteria andGcFactoryIsNull() {
            addCriterion("gc_factory is null");
            return (Criteria) this;
        }

        public Criteria andGcFactoryIsNotNull() {
            addCriterion("gc_factory is not null");
            return (Criteria) this;
        }

        public Criteria andGcFactoryEqualTo(String value) {
            addCriterion("gc_factory =", value, "gcFactory");
            return (Criteria) this;
        }

        public Criteria andGcFactoryNotEqualTo(String value) {
            addCriterion("gc_factory <>", value, "gcFactory");
            return (Criteria) this;
        }

        public Criteria andGcFactoryGreaterThan(String value) {
            addCriterion("gc_factory >", value, "gcFactory");
            return (Criteria) this;
        }

        public Criteria andGcFactoryGreaterThanOrEqualTo(String value) {
            addCriterion("gc_factory >=", value, "gcFactory");
            return (Criteria) this;
        }

        public Criteria andGcFactoryLessThan(String value) {
            addCriterion("gc_factory <", value, "gcFactory");
            return (Criteria) this;
        }

        public Criteria andGcFactoryLessThanOrEqualTo(String value) {
            addCriterion("gc_factory <=", value, "gcFactory");
            return (Criteria) this;
        }

        public Criteria andGcFactoryLike(String value) {
            addCriterion("gc_factory like", value, "gcFactory");
            return (Criteria) this;
        }

        public Criteria andGcFactoryNotLike(String value) {
            addCriterion("gc_factory not like", value, "gcFactory");
            return (Criteria) this;
        }

        public Criteria andGcFactoryIn(List<String> values) {
            addCriterion("gc_factory in", values, "gcFactory");
            return (Criteria) this;
        }

        public Criteria andGcFactoryNotIn(List<String> values) {
            addCriterion("gc_factory not in", values, "gcFactory");
            return (Criteria) this;
        }

        public Criteria andGcFactoryBetween(String value1, String value2) {
            addCriterion("gc_factory between", value1, value2, "gcFactory");
            return (Criteria) this;
        }

        public Criteria andGcFactoryNotBetween(String value1, String value2) {
            addCriterion("gc_factory not between", value1, value2, "gcFactory");
            return (Criteria) this;
        }

        public Criteria andGcParamIsNull() {
            addCriterion("gc_param is null");
            return (Criteria) this;
        }

        public Criteria andGcParamIsNotNull() {
            addCriterion("gc_param is not null");
            return (Criteria) this;
        }

        public Criteria andGcParamEqualTo(String value) {
            addCriterion("gc_param =", value, "gcParam");
            return (Criteria) this;
        }

        public Criteria andGcParamNotEqualTo(String value) {
            addCriterion("gc_param <>", value, "gcParam");
            return (Criteria) this;
        }

        public Criteria andGcParamGreaterThan(String value) {
            addCriterion("gc_param >", value, "gcParam");
            return (Criteria) this;
        }

        public Criteria andGcParamGreaterThanOrEqualTo(String value) {
            addCriterion("gc_param >=", value, "gcParam");
            return (Criteria) this;
        }

        public Criteria andGcParamLessThan(String value) {
            addCriterion("gc_param <", value, "gcParam");
            return (Criteria) this;
        }

        public Criteria andGcParamLessThanOrEqualTo(String value) {
            addCriterion("gc_param <=", value, "gcParam");
            return (Criteria) this;
        }

        public Criteria andGcParamLike(String value) {
            addCriterion("gc_param like", value, "gcParam");
            return (Criteria) this;
        }

        public Criteria andGcParamNotLike(String value) {
            addCriterion("gc_param not like", value, "gcParam");
            return (Criteria) this;
        }

        public Criteria andGcParamIn(List<String> values) {
            addCriterion("gc_param in", values, "gcParam");
            return (Criteria) this;
        }

        public Criteria andGcParamNotIn(List<String> values) {
            addCriterion("gc_param not in", values, "gcParam");
            return (Criteria) this;
        }

        public Criteria andGcParamBetween(String value1, String value2) {
            addCriterion("gc_param between", value1, value2, "gcParam");
            return (Criteria) this;
        }

        public Criteria andGcParamNotBetween(String value1, String value2) {
            addCriterion("gc_param not between", value1, value2, "gcParam");
            return (Criteria) this;
        }

        public Criteria andGcPriceIsNull() {
            addCriterion("gc_price is null");
            return (Criteria) this;
        }

        public Criteria andGcPriceIsNotNull() {
            addCriterion("gc_price is not null");
            return (Criteria) this;
        }

        public Criteria andGcPriceEqualTo(Double value) {
            addCriterion("gc_price =", value, "gcPrice");
            return (Criteria) this;
        }

        public Criteria andGcPriceNotEqualTo(Double value) {
            addCriterion("gc_price <>", value, "gcPrice");
            return (Criteria) this;
        }

        public Criteria andGcPriceGreaterThan(Double value) {
            addCriterion("gc_price >", value, "gcPrice");
            return (Criteria) this;
        }

        public Criteria andGcPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("gc_price >=", value, "gcPrice");
            return (Criteria) this;
        }

        public Criteria andGcPriceLessThan(Double value) {
            addCriterion("gc_price <", value, "gcPrice");
            return (Criteria) this;
        }

        public Criteria andGcPriceLessThanOrEqualTo(Double value) {
            addCriterion("gc_price <=", value, "gcPrice");
            return (Criteria) this;
        }

        public Criteria andGcPriceIn(List<Double> values) {
            addCriterion("gc_price in", values, "gcPrice");
            return (Criteria) this;
        }

        public Criteria andGcPriceNotIn(List<Double> values) {
            addCriterion("gc_price not in", values, "gcPrice");
            return (Criteria) this;
        }

        public Criteria andGcPriceBetween(Double value1, Double value2) {
            addCriterion("gc_price between", value1, value2, "gcPrice");
            return (Criteria) this;
        }

        public Criteria andGcPriceNotBetween(Double value1, Double value2) {
            addCriterion("gc_price not between", value1, value2, "gcPrice");
            return (Criteria) this;
        }

        public Criteria andGcInventoryIsNull() {
            addCriterion("gc_inventory is null");
            return (Criteria) this;
        }

        public Criteria andGcInventoryIsNotNull() {
            addCriterion("gc_inventory is not null");
            return (Criteria) this;
        }

        public Criteria andGcInventoryEqualTo(Integer value) {
            addCriterion("gc_inventory =", value, "gcInventory");
            return (Criteria) this;
        }

        public Criteria andGcInventoryNotEqualTo(Integer value) {
            addCriterion("gc_inventory <>", value, "gcInventory");
            return (Criteria) this;
        }

        public Criteria andGcInventoryGreaterThan(Integer value) {
            addCriterion("gc_inventory >", value, "gcInventory");
            return (Criteria) this;
        }

        public Criteria andGcInventoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("gc_inventory >=", value, "gcInventory");
            return (Criteria) this;
        }

        public Criteria andGcInventoryLessThan(Integer value) {
            addCriterion("gc_inventory <", value, "gcInventory");
            return (Criteria) this;
        }

        public Criteria andGcInventoryLessThanOrEqualTo(Integer value) {
            addCriterion("gc_inventory <=", value, "gcInventory");
            return (Criteria) this;
        }

        public Criteria andGcInventoryIn(List<Integer> values) {
            addCriterion("gc_inventory in", values, "gcInventory");
            return (Criteria) this;
        }

        public Criteria andGcInventoryNotIn(List<Integer> values) {
            addCriterion("gc_inventory not in", values, "gcInventory");
            return (Criteria) this;
        }

        public Criteria andGcInventoryBetween(Integer value1, Integer value2) {
            addCriterion("gc_inventory between", value1, value2, "gcInventory");
            return (Criteria) this;
        }

        public Criteria andGcInventoryNotBetween(Integer value1, Integer value2) {
            addCriterion("gc_inventory not between", value1, value2, "gcInventory");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table graphics_card
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 07 22:26:32 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table graphics_card
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}