package com.ch.computer.pojo;

public class GraphicsCard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graphics_card.gc_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Integer gcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graphics_card.gc_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String gcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graphics_card.gc_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String gcFactory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graphics_card.gc_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String gcParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graphics_card.gc_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Double gcPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graphics_card.gc_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Integer gcInventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graphics_card.gc_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String gcImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graphics_card.gc_id
     *
     * @return the value of graphics_card.gc_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Integer getGcId() {
        return gcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graphics_card.gc_id
     *
     * @param gcId the value for graphics_card.gc_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setGcId(Integer gcId) {
        this.gcId = gcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graphics_card.gc_name
     *
     * @return the value of graphics_card.gc_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getGcName() {
        return gcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graphics_card.gc_name
     *
     * @param gcName the value for graphics_card.gc_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setGcName(String gcName) {
        this.gcName = gcName == null ? null : gcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graphics_card.gc_factory
     *
     * @return the value of graphics_card.gc_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getGcFactory() {
        return gcFactory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graphics_card.gc_factory
     *
     * @param gcFactory the value for graphics_card.gc_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setGcFactory(String gcFactory) {
        this.gcFactory = gcFactory == null ? null : gcFactory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graphics_card.gc_param
     *
     * @return the value of graphics_card.gc_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getGcParam() {
        return gcParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graphics_card.gc_param
     *
     * @param gcParam the value for graphics_card.gc_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setGcParam(String gcParam) {
        this.gcParam = gcParam == null ? null : gcParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graphics_card.gc_price
     *
     * @return the value of graphics_card.gc_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Double getGcPrice() {
        return gcPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graphics_card.gc_price
     *
     * @param gcPrice the value for graphics_card.gc_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setGcPrice(Double gcPrice) {
        this.gcPrice = gcPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graphics_card.gc_inventory
     *
     * @return the value of graphics_card.gc_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Integer getGcInventory() {
        return gcInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graphics_card.gc_inventory
     *
     * @param gcInventory the value for graphics_card.gc_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setGcInventory(Integer gcInventory) {
        this.gcInventory = gcInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graphics_card.gc_img
     *
     * @return the value of graphics_card.gc_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getGcImg() {
        return gcImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graphics_card.gc_img
     *
     * @param gcImg the value for graphics_card.gc_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setGcImg(String gcImg) {
        this.gcImg = gcImg == null ? null : gcImg.trim();
    }
}