package com.ch.computer.pojo;

public class HeatDissipation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heat_dissipation.h_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Integer hId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heat_dissipation.h_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String hName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heat_dissipation.h_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String hFactory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heat_dissipation.h_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String hParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heat_dissipation.h_type
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Integer hType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heat_dissipation.h_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Double hPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heat_dissipation.h_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Integer hInventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heat_dissipation.h_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String hImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heat_dissipation.h_id
     *
     * @return the value of heat_dissipation.h_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Integer gethId() {
        return hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heat_dissipation.h_id
     *
     * @param hId the value for heat_dissipation.h_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void sethId(Integer hId) {
        this.hId = hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heat_dissipation.h_name
     *
     * @return the value of heat_dissipation.h_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String gethName() {
        return hName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heat_dissipation.h_name
     *
     * @param hName the value for heat_dissipation.h_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void sethName(String hName) {
        this.hName = hName == null ? null : hName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heat_dissipation.h_factory
     *
     * @return the value of heat_dissipation.h_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String gethFactory() {
        return hFactory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heat_dissipation.h_factory
     *
     * @param hFactory the value for heat_dissipation.h_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void sethFactory(String hFactory) {
        this.hFactory = hFactory == null ? null : hFactory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heat_dissipation.h_param
     *
     * @return the value of heat_dissipation.h_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String gethParam() {
        return hParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heat_dissipation.h_param
     *
     * @param hParam the value for heat_dissipation.h_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void sethParam(String hParam) {
        this.hParam = hParam == null ? null : hParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heat_dissipation.h_type
     *
     * @return the value of heat_dissipation.h_type
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Integer gethType() {
        return hType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heat_dissipation.h_type
     *
     * @param hType the value for heat_dissipation.h_type
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void sethType(Integer hType) {
        this.hType = hType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heat_dissipation.h_price
     *
     * @return the value of heat_dissipation.h_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Double gethPrice() {
        return hPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heat_dissipation.h_price
     *
     * @param hPrice the value for heat_dissipation.h_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void sethPrice(Double hPrice) {
        this.hPrice = hPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heat_dissipation.h_inventory
     *
     * @return the value of heat_dissipation.h_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Integer gethInventory() {
        return hInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heat_dissipation.h_inventory
     *
     * @param hInventory the value for heat_dissipation.h_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void sethInventory(Integer hInventory) {
        this.hInventory = hInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heat_dissipation.h_img
     *
     * @return the value of heat_dissipation.h_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String gethImg() {
        return hImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heat_dissipation.h_img
     *
     * @param hImg the value for heat_dissipation.h_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void sethImg(String hImg) {
        this.hImg = hImg == null ? null : hImg.trim();
    }
}