package com.ch.computer.pojo;

public class Mainboard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainboard.mb_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Integer mbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainboard.mb_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String mbName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainboard.mb_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String mbFactory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainboard.mb_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String mbParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainboard.mb_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Double mbPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainboard.mb_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Integer mbInventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainboard.mb_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String mbImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainboard.mb_id
     *
     * @return the value of mainboard.mb_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Integer getMbId() {
        return mbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainboard.mb_id
     *
     * @param mbId the value for mainboard.mb_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setMbId(Integer mbId) {
        this.mbId = mbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainboard.mb_name
     *
     * @return the value of mainboard.mb_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getMbName() {
        return mbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainboard.mb_name
     *
     * @param mbName the value for mainboard.mb_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setMbName(String mbName) {
        this.mbName = mbName == null ? null : mbName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainboard.mb_factory
     *
     * @return the value of mainboard.mb_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getMbFactory() {
        return mbFactory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainboard.mb_factory
     *
     * @param mbFactory the value for mainboard.mb_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setMbFactory(String mbFactory) {
        this.mbFactory = mbFactory == null ? null : mbFactory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainboard.mb_param
     *
     * @return the value of mainboard.mb_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getMbParam() {
        return mbParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainboard.mb_param
     *
     * @param mbParam the value for mainboard.mb_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setMbParam(String mbParam) {
        this.mbParam = mbParam == null ? null : mbParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainboard.mb_price
     *
     * @return the value of mainboard.mb_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Double getMbPrice() {
        return mbPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainboard.mb_price
     *
     * @param mbPrice the value for mainboard.mb_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setMbPrice(Double mbPrice) {
        this.mbPrice = mbPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainboard.mb_inventory
     *
     * @return the value of mainboard.mb_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Integer getMbInventory() {
        return mbInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainboard.mb_inventory
     *
     * @param mbInventory the value for mainboard.mb_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setMbInventory(Integer mbInventory) {
        this.mbInventory = mbInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainboard.mb_img
     *
     * @return the value of mainboard.mb_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getMbImg() {
        return mbImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainboard.mb_img
     *
     * @param mbImg the value for mainboard.mb_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setMbImg(String mbImg) {
        this.mbImg = mbImg == null ? null : mbImg.trim();
    }
}