package com.ch.computer.pojo;

public class Memory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memory.m_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Integer mId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memory.m_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String mName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memory.m_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String mFactory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memory.m_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String mParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memory.m_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Double mPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memory.m_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Integer mInventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memory.m_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String mImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memory.m_id
     *
     * @return the value of memory.m_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memory.m_id
     *
     * @param mId the value for memory.m_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memory.m_name
     *
     * @return the value of memory.m_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getmName() {
        return mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memory.m_name
     *
     * @param mName the value for memory.m_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setmName(String mName) {
        this.mName = mName == null ? null : mName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memory.m_factory
     *
     * @return the value of memory.m_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getmFactory() {
        return mFactory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memory.m_factory
     *
     * @param mFactory the value for memory.m_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setmFactory(String mFactory) {
        this.mFactory = mFactory == null ? null : mFactory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memory.m_param
     *
     * @return the value of memory.m_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getmParam() {
        return mParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memory.m_param
     *
     * @param mParam the value for memory.m_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setmParam(String mParam) {
        this.mParam = mParam == null ? null : mParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memory.m_price
     *
     * @return the value of memory.m_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Double getmPrice() {
        return mPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memory.m_price
     *
     * @param mPrice the value for memory.m_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setmPrice(Double mPrice) {
        this.mPrice = mPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memory.m_inventory
     *
     * @return the value of memory.m_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Integer getmInventory() {
        return mInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memory.m_inventory
     *
     * @param mInventory the value for memory.m_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setmInventory(Integer mInventory) {
        this.mInventory = mInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memory.m_img
     *
     * @return the value of memory.m_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getmImg() {
        return mImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memory.m_img
     *
     * @param mImg the value for memory.m_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setmImg(String mImg) {
        this.mImg = mImg == null ? null : mImg.trim();
    }
}