package com.ch.computer.pojo;

public class Source {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source.s_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Integer sId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source.s_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String sName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source.s_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String sFactory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source.s_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String sParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source.s_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Double sPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source.s_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Integer sInventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source.s_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String sImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source.s_id
     *
     * @return the value of source.s_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source.s_id
     *
     * @param sId the value for source.s_id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source.s_name
     *
     * @return the value of source.s_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source.s_name
     *
     * @param sName the value for source.s_name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source.s_factory
     *
     * @return the value of source.s_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getsFactory() {
        return sFactory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source.s_factory
     *
     * @param sFactory the value for source.s_factory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setsFactory(String sFactory) {
        this.sFactory = sFactory == null ? null : sFactory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source.s_param
     *
     * @return the value of source.s_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getsParam() {
        return sParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source.s_param
     *
     * @param sParam the value for source.s_param
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setsParam(String sParam) {
        this.sParam = sParam == null ? null : sParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source.s_price
     *
     * @return the value of source.s_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Double getsPrice() {
        return sPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source.s_price
     *
     * @param sPrice the value for source.s_price
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setsPrice(Double sPrice) {
        this.sPrice = sPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source.s_inventory
     *
     * @return the value of source.s_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Integer getsInventory() {
        return sInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source.s_inventory
     *
     * @param sInventory the value for source.s_inventory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setsInventory(Integer sInventory) {
        this.sInventory = sInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source.s_img
     *
     * @return the value of source.s_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getsImg() {
        return sImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source.s_img
     *
     * @param sImg the value for source.s_img
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setsImg(String sImg) {
        this.sImg = sImg == null ? null : sImg.trim();
    }
}