package com.ch.computer.pojo;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.password
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.phone
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.email
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.register_time
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.user_type
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    private Integer userType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.id
     *
     * @return the value of c_user.id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.id
     *
     * @param id the value for c_user.id
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.name
     *
     * @return the value of c_user.name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.name
     *
     * @param name the value for c_user.name
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.password
     *
     * @return the value of c_user.password
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.password
     *
     * @param password the value for c_user.password
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.phone
     *
     * @return the value of c_user.phone
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.phone
     *
     * @param phone the value for c_user.phone
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.email
     *
     * @return the value of c_user.email
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.email
     *
     * @param email the value for c_user.email
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.register_time
     *
     * @return the value of c_user.register_time
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.register_time
     *
     * @param registerTime the value for c_user.register_time
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.user_type
     *
     * @return the value of c_user.user_type
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.user_type
     *
     * @param userType the value for c_user.user_type
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }
}