package com.ch.computer.mapper;

import com.ch.computer.pojo.Chassis;
import com.ch.computer.pojo.ChassisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChassisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int countByExample(ChassisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int deleteByExample(ChassisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int deleteByPrimaryKey(Integer chId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int insert(Chassis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int insertSelective(Chassis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    List<Chassis> selectByExampleWithBLOBs(ChassisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    List<Chassis> selectByExample(ChassisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    Chassis selectByPrimaryKey(Integer chId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByExampleSelective(@Param("record") Chassis record, @Param("example") ChassisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") Chassis record, @Param("example") ChassisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByExample(@Param("record") Chassis record, @Param("example") ChassisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByPrimaryKeySelective(Chassis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(Chassis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByPrimaryKey(Chassis record);
}