package com.ch.computer.mapper;

import com.ch.computer.pojo.Cpu;
import com.ch.computer.pojo.CpuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CpuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpu
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int countByExample(CpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpu
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int deleteByExample(CpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpu
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int deleteByPrimaryKey(Integer cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpu
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int insert(Cpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpu
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int insertSelective(Cpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpu
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    List<Cpu> selectByExampleWithBLOBs(CpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpu
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    List<Cpu> selectByExample(CpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpu
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    Cpu selectByPrimaryKey(Integer cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpu
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByExampleSelective(@Param("record") Cpu record, @Param("example") CpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpu
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") Cpu record, @Param("example") CpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpu
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByExample(@Param("record") Cpu record, @Param("example") CpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpu
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByPrimaryKeySelective(Cpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpu
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(Cpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpu
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByPrimaryKey(Cpu record);
}