package com.ch.computer.mapper;

import com.ch.computer.pojo.Disk;
import com.ch.computer.pojo.DiskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DiskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disk
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int countByExample(DiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disk
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int deleteByExample(DiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disk
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int deleteByPrimaryKey(Integer dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disk
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int insert(Disk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disk
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int insertSelective(Disk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disk
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    List<Disk> selectByExampleWithBLOBs(DiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disk
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    List<Disk> selectByExample(DiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disk
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    Disk selectByPrimaryKey(Integer dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disk
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByExampleSelective(@Param("record") Disk record, @Param("example") DiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disk
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") Disk record, @Param("example") DiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disk
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByExample(@Param("record") Disk record, @Param("example") DiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disk
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByPrimaryKeySelective(Disk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disk
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(Disk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disk
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByPrimaryKey(Disk record);
}