package com.ch.computer.mapper;

import com.ch.computer.pojo.Fan;
import com.ch.computer.pojo.FanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fan
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int countByExample(FanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fan
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int deleteByExample(FanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fan
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int deleteByPrimaryKey(Integer fId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fan
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int insert(Fan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fan
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int insertSelective(Fan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fan
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    List<Fan> selectByExampleWithBLOBs(FanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fan
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    List<Fan> selectByExample(FanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fan
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    Fan selectByPrimaryKey(Integer fId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fan
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByExampleSelective(@Param("record") Fan record, @Param("example") FanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fan
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") Fan record, @Param("example") FanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fan
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByExample(@Param("record") Fan record, @Param("example") FanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fan
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByPrimaryKeySelective(Fan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fan
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(Fan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fan
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByPrimaryKey(Fan record);
}