package com.ch.computer.mapper;

import com.ch.computer.pojo.Memory;
import com.ch.computer.pojo.MemoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int countByExample(MemoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int deleteByExample(MemoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int deleteByPrimaryKey(Integer mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int insert(Memory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int insertSelective(Memory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    List<Memory> selectByExampleWithBLOBs(MemoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    List<Memory> selectByExample(MemoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    Memory selectByPrimaryKey(Integer mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByExampleSelective(@Param("record") Memory record, @Param("example") MemoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") Memory record, @Param("example") MemoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByExample(@Param("record") Memory record, @Param("example") MemoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByPrimaryKeySelective(Memory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(Memory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByPrimaryKey(Memory record);
}