package com.ch.computer.mapper;

import com.ch.computer.pojo.ShopCart;
import com.ch.computer.pojo.ShopCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated Fri Aug 11 22:26:09 CST 2023
     */
    int countByExample(ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated Fri Aug 11 22:26:09 CST 2023
     */
    int deleteByExample(ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated Fri Aug 11 22:26:09 CST 2023
     */
    int deleteByPrimaryKey(Integer scId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated Fri Aug 11 22:26:09 CST 2023
     */
    int insert(ShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated Fri Aug 11 22:26:09 CST 2023
     */
    int insertSelective(ShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated Fri Aug 11 22:26:09 CST 2023
     */
    List<ShopCart> selectByExample(ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated Fri Aug 11 22:26:09 CST 2023
     */
    ShopCart selectByPrimaryKey(Integer scId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated Fri Aug 11 22:26:09 CST 2023
     */
    int updateByExampleSelective(@Param("record") ShopCart record, @Param("example") ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated Fri Aug 11 22:26:09 CST 2023
     */
    int updateByExample(@Param("record") ShopCart record, @Param("example") ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated Fri Aug 11 22:26:09 CST 2023
     */
    int updateByPrimaryKeySelective(ShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated Fri Aug 11 22:26:09 CST 2023
     */
    int updateByPrimaryKey(ShopCart record);
}