package com.ch.computer.mapper;

import com.ch.computer.pojo.Source;
import com.ch.computer.pojo.SourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int countByExample(SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int deleteByExample(SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int deleteByPrimaryKey(Integer sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int insert(Source record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int insertSelective(Source record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    List<Source> selectByExampleWithBLOBs(SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    List<Source> selectByExample(SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    Source selectByPrimaryKey(Integer sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByExampleSelective(@Param("record") Source record, @Param("example") SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") Source record, @Param("example") SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByExample(@Param("record") Source record, @Param("example") SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByPrimaryKeySelective(Source record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(Source record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated Mon Aug 07 22:26:32 CST 2023
     */
    int updateByPrimaryKey(Source record);
}